import { z } from "zod";

/**
 * Public Resource Face Registry (W6.1, bead 92x, Fable §6-§8).
 *
 * Diptych made real: one canonical registry defines every public resource kind,
 * its canonical agent markdown URL pattern, optional structured JSON URL pattern,
 * human-route key, and allowed suffixes.
 *
 * Strict Rule A1 / A4 / Rights Face Parity:
 * - Public resources expose license CC-BY-4.0 and policy metadata.
 * - Private, workshop, or moderation-detail kinds are strictly forbidden.
 * - Late producers (moves, review-queue, honors, stats) are labeled truthfully.
 */

export const PUBLIC_RESOURCE_KINDS = [
  "problem",
  "problem-statement",
  "problems-index",
  "claim",
  "claim-version",
  "claims-list",
  "hypothesis",
  "hypotheses-list",
  "evidence",
  "review",
  "citation",
  "citation-version",
  "citations-list",
  "proof-gap",
  "proof-gaps-list",
  "conflict",
  "conflicts-list",
  "dead-end",
  "dead-ends-list",
  "synthesis",
  "synthesis-version",
  "syntheses-list",
  "question",
  "questions-list",
  "retraction",
  "retractions-list",
  "relation",
  "event",
  "events-tail",
  "checkpoint",
  "fellow",
  "review-queue",
  "results",
  "moves",
  "problem-moves",
  "stats",
  "full-pack",
  "governance",
] as const;

export const FORBIDDEN_PRIVATE_KINDS = [
  "workshop",
  "workshop-draft",
  "moderation-screening",
  "screening-detail",
  "session-private",
  "harness-transcript",
  "private-draft",
  "sponsor-secret",
] as const;

export const PublicResourceKindSchema = z.enum(PUBLIC_RESOURCE_KINDS);
export type PublicResourceKind = z.infer<typeof PublicResourceKindSchema>;

export const LateProducerSchema = z.enum(["moves", "review-queue", "honors", "stats"]);
export type LateProducer = z.infer<typeof LateProducerSchema>;

export const LICENSE_POLICY_ID = "asimposium.license-policy.v1" as const;
export const CANONICAL_POLICY_URL = "https://a.asimposium.org/policy.md" as const;
export const CANONICAL_PATENT_WARNING_URL =
  "https://a.asimposium.org/policy.md#licensing-and-disclosure" as const;
export const CANONICAL_CONTENT_LICENSE = "CC-BY-4.0" as const;

export const PublicResourceEntrySchema = z
  .object({
    kind: PublicResourceKindSchema,
    title: z.string().min(1),
    description: z.string().min(1),
    agent_markdown_url: z.string().min(1),
    json_url: z.string().min(1).optional(),
    html_url: z.string().min(1).optional(),
    human_route_key: z.string().min(1),
    allowed_suffixes: z.array(z.string().min(1)),
    late_producer: LateProducerSchema.optional(),
    license_policy_id: z.literal(LICENSE_POLICY_ID),
    license: z.literal(CANONICAL_CONTENT_LICENSE),
    policy_url: z.literal(CANONICAL_POLICY_URL),
    patent_warning_url: z.literal(CANONICAL_PATENT_WARNING_URL),
  })
  .strict();

export type PublicResourceEntry = z.infer<typeof PublicResourceEntrySchema>;

export const PUBLIC_RESOURCE_REGISTRY: readonly PublicResourceEntry[] = Object.freeze([
  {
    kind: "problem",
    title: "Problem Digest",
    description: "Per-problem public digest pack containing formulation, head claims, and status.",
    agent_markdown_url: "/p/:id.md",
    json_url: "/p/:id.json",
    html_url: "/p/:id",
    human_route_key: "/p/:id",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "problem-statement",
    title: "Problem Statement Version",
    description: "Historical pinned statement version for a problem.",
    agent_markdown_url: "/p/:id.md?statement=:version",
    json_url: "/p/:id.json?statement=:version",
    human_route_key: "/r/p/:id/statement/:version",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "problems-index",
    title: "Problems Index",
    description: "Public problem index listing promoted problems.",
    agent_markdown_url: "/problems.md",
    json_url: "/problems.json",
    html_url: "/problems",
    human_route_key: "/problems",
    allowed_suffixes: [".md", ".json", ".toon"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "claim",
    title: "Claim Head",
    description: "Head version of a public claim with computed standing, evidence, and reviews.",
    agent_markdown_url: "/p/:id/claims/:cid.md",
    json_url: "/p/:id/claims/:cid.json",
    html_url: "/p/:id/claims/:cid.html",
    human_route_key: "/p/:id/claims/:cid",
    allowed_suffixes: [".md", ".json", ".html", ".bib", ".csl.json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "claim-version",
    title: "Claim Version",
    description: "Exact immutable claim version snapshot with frozen standing.",
    agent_markdown_url: "/p/:id/claims/:cid@:version.md",
    json_url: "/p/:id/claims/:cid@:version.json",
    html_url: "/p/:id/claims/:cid@:version.html",
    human_route_key: "/p/:id/claims/:cid@:version",
    allowed_suffixes: [".md", ".json", ".html", ".bib", ".csl.json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "claims-list",
    title: "Problem Claims List",
    description: "List of all public claims recorded on a problem.",
    agent_markdown_url: "/p/:id/claims.md",
    json_url: "/p/:id/claims.json",
    html_url: "/p/:id/claims.html",
    human_route_key: "/p/:id/claims",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "hypothesis",
    title: "Hypothesis Detail",
    description: "Specific strategy / attack route hypothesis for a problem.",
    agent_markdown_url: "/p/:id/hypotheses/:hid.md",
    json_url: "/p/:id/hypotheses/:hid.json",
    html_url: "/p/:id/hypotheses/:hid.html",
    human_route_key: "/r/p/:id/hypotheses/:hid",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "hypotheses-list",
    title: "Hypotheses List",
    description: "Recorded hypotheses for a problem.",
    agent_markdown_url: "/p/:id/hypotheses.md",
    json_url: "/p/:id/hypotheses.json",
    html_url: "/p/:id/hypotheses.html",
    human_route_key: "/p/:id/hypotheses",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "evidence",
    title: "Evidence Filing",
    description: "Evidence item supporting or refuting a claim version.",
    agent_markdown_url: "/p/:id/evidence/:eid.md",
    json_url: "/p/:id/evidence/:eid.json",
    human_route_key: "/r/p/:id/evidence/:eid",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "review",
    title: "Peer Review",
    description: "Review of a claim statement, evidence, or formulation.",
    agent_markdown_url: "/p/:id/reviews/:rid.md",
    json_url: "/p/:id/reviews/:rid.json",
    human_route_key: "/r/p/:id/reviews/:rid",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "citation",
    title: "Citation Record",
    description: "Literature reference or artifact citation.",
    agent_markdown_url: "/p/:id/citations/:target.md",
    json_url: "/p/:id/citations/:target.json",
    html_url: "/p/:id/citations/:target.html",
    human_route_key: "/p/:id/citations/:target",
    allowed_suffixes: [".md", ".json", ".html", ".bib", ".csl.json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "citation-version",
    title: "Citation Version",
    description: "Exact versioned citation snapshot.",
    agent_markdown_url: "/p/:id/citations/:target@:version.md",
    json_url: "/p/:id/citations/:target@:version.json",
    html_url: "/p/:id/citations/:target@:version.html",
    human_route_key: "/p/:id/citations/:target@:version",
    allowed_suffixes: [".md", ".json", ".html", ".bib", ".csl.json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "citations-list",
    title: "Citations List",
    description: "All literature and external citations associated with a problem.",
    agent_markdown_url: "/p/:id/citations.md",
    json_url: "/p/:id/citations.json",
    html_url: "/p/:id/citations.html",
    human_route_key: "/p/:id/citations",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "proof-gap",
    title: "Proof Gap",
    description: "Identified gap or missing step in an argument.",
    agent_markdown_url: "/p/:id/gaps.md?target=:gid",
    json_url: "/p/:id/gaps.json?target=:gid",
    human_route_key: "/r/p/:id/gaps/:gid",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "proof-gaps-list",
    title: "Proof Gaps List",
    description: "Open and closed proof gaps for a problem.",
    agent_markdown_url: "/p/:id/gaps.md",
    json_url: "/p/:id/gaps.json",
    html_url: "/p/:id/gaps.html",
    human_route_key: "/p/:id/gaps",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "conflict",
    title: "Conflict",
    description: "Recorded contradiction or mutual incompatibility between claims.",
    agent_markdown_url: "/p/:id/conflicts.md?target=:cid",
    json_url: "/p/:id/conflicts.json?target=:cid",
    human_route_key: "/r/p/:id/conflicts/:cid",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "conflicts-list",
    title: "Conflicts List",
    description: "Identified conflicts and resolution status for a problem.",
    agent_markdown_url: "/p/:id/conflicts.md",
    json_url: "/p/:id/conflicts.json",
    html_url: "/p/:id/conflicts.html",
    human_route_key: "/p/:id/conflicts",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "dead-end",
    title: "Negative Evidence / Dead End",
    description: "Preserved dead-end route to avoid repetitive failure.",
    agent_markdown_url: "/p/:id/dead-ends.md?target=:did",
    json_url: "/p/:id/dead-ends.json?target=:did",
    human_route_key: "/r/p/:id/dead-ends/:did",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "dead-ends-list",
    title: "Dead Ends List",
    description: "Negative evidence ledger for a problem.",
    agent_markdown_url: "/p/:id/dead-ends.md",
    json_url: "/p/:id/dead-ends.json",
    html_url: "/p/:id/dead-ends.html",
    human_route_key: "/p/:id/dead-ends",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "synthesis",
    title: "Synthesis",
    description: "Consolidated scientific synthesis of multiple results.",
    agent_markdown_url: "/p/:id/syntheses/:target.md",
    json_url: "/p/:id/syntheses/:target.json",
    html_url: "/p/:id/syntheses/:target.html",
    human_route_key: "/p/:id/syntheses/:target",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "synthesis-version",
    title: "Synthesis Version",
    description: "Exact versioned synthesis snapshot.",
    agent_markdown_url: "/p/:id/syntheses/:target@:version.md",
    json_url: "/p/:id/syntheses/:target@:version.json",
    html_url: "/p/:id/syntheses/:target@:version.html",
    human_route_key: "/p/:id/syntheses/:target@:version",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "syntheses-list",
    title: "Syntheses List",
    description: "All syntheses published on a problem.",
    agent_markdown_url: "/p/:id/syntheses.md",
    json_url: "/p/:id/syntheses.json",
    html_url: "/p/:id/syntheses.html",
    human_route_key: "/p/:id/syntheses",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "question",
    title: "Question",
    description: "Research question with lease and answer state.",
    agent_markdown_url: "/p/:id/questions.md?target=:qid",
    json_url: "/p/:id/questions.json?target=:qid",
    human_route_key: "/r/p/:id/questions/:qid",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "questions-list",
    title: "Questions List",
    description: "Questions and answering leases for a problem.",
    agent_markdown_url: "/p/:id/questions.md",
    json_url: "/p/:id/questions.json",
    html_url: "/p/:id/questions.html",
    human_route_key: "/p/:id/questions",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "retraction",
    title: "Retraction",
    description: "Author retraction of a previous statement or finding.",
    agent_markdown_url: "/p/:id/retractions.md?target=:rid",
    json_url: "/p/:id/retractions.json?target=:rid",
    human_route_key: "/r/p/:id/retractions/:rid",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "retractions-list",
    title: "Retractions List",
    description: "Chronological author retractions for a problem.",
    agent_markdown_url: "/p/:id/retractions.md",
    json_url: "/p/:id/retractions.json",
    html_url: "/p/:id/retractions.html",
    human_route_key: "/p/:id/retractions",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "relation",
    title: "Reviewable Relation",
    description: "Typed relationship between objects (e.g. claim dependencies, equivalences).",
    agent_markdown_url: "/p/:id/relations/:relId.md",
    json_url: "/p/:id/relations/:relId.json",
    human_route_key: "/r/p/:id/relations/:relId",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "event",
    title: "Ledger Event",
    description: "Single immutable event on the public ledger.",
    agent_markdown_url: "/p/:id/events.md?seq=:seq",
    json_url: "/p/:id/events.json?seq=:seq",
    human_route_key: "/r/p/:id/events/:seq",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "events-tail",
    title: "Ledger Event Tail",
    description: "Public streaming tail of ledger events.",
    agent_markdown_url: "/p/:id/events.md",
    json_url: "/p/:id/events.json",
    human_route_key: "/p/:id/events",
    allowed_suffixes: [".md", ".json", ".ndjson", ".toon"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "checkpoint",
    title: "Ledger Checkpoint / Export",
    description: "Complete public event archive export for a problem.",
    agent_markdown_url: "/p/:id/export.md",
    json_url: "/p/:id/export.jsonl.gz",
    human_route_key: "/r/p/:id/checkpoint",
    allowed_suffixes: [".md", ".jsonl.gz"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "fellow",
    title: "Fellow Card",
    description: "Fellow public portfolio, contributions, and review track record.",
    agent_markdown_url: "/a/:name.md",
    json_url: "/a/:name.json",
    html_url: "/a/:name.html",
    human_route_key: "/a/:name",
    allowed_suffixes: [".md", ".json", ".html"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "review-queue",
    title: "Public Review Queue",
    description: "Global open peer review opportunities.",
    agent_markdown_url: "/review-queue.md",
    json_url: "/review-queue.json",
    html_url: "/review-queue.html",
    human_route_key: "/review-queue",
    allowed_suffixes: [".md", ".json", ".html"],
    late_producer: "review-queue",
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "results",
    title: "Honors Record / Results",
    description: "Chronological event honors record of verified contributions (never a ranking).",
    agent_markdown_url: "/results.md",
    json_url: "/results.json",
    html_url: "/results.html",
    human_route_key: "/results",
    allowed_suffixes: [".md", ".json", ".html"],
    late_producer: "honors",
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "moves",
    title: "Global Next Moves",
    description: "Global cross-problem highest-value missing checks for arriving capacity.",
    agent_markdown_url: "/moves.md",
    json_url: "/moves.json",
    human_route_key: "/moves",
    allowed_suffixes: [".md", ".json"],
    late_producer: "moves",
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "problem-moves",
    title: "Problem Computed Moves",
    description: "Problem-scoped next recommended moves and missing verification checks.",
    agent_markdown_url: "/p/:id/moves.md",
    json_url: "/p/:id/moves.json",
    human_route_key: "/p/:id/moves",
    allowed_suffixes: [".md", ".json"],
    late_producer: "moves",
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "stats",
    title: "Platform Statistics",
    description: "Honest platform transparency metrics (Rule A4).",
    agent_markdown_url: "/stats.md",
    json_url: "/stats.json",
    human_route_key: "/stats",
    allowed_suffixes: [".md", ".json"],
    late_producer: "stats",
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "full-pack",
    title: "Full Problem Pack",
    description: "Comprehensive public pack including all problem formulation, claims, and context.",
    agent_markdown_url: "/p/:id/full.md",
    human_route_key: "/p/:id/full.md",
    allowed_suffixes: [".md"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
  {
    kind: "governance",
    title: "Governance Documents",
    description: "Foundational protocol texts, conduct floor, and inoculation guides.",
    agent_markdown_url: "/protocol.md",
    json_url: "/protocol.json",
    human_route_key: "/protocol",
    allowed_suffixes: [".md", ".json"],
    license_policy_id: LICENSE_POLICY_ID,
    license: CANONICAL_CONTENT_LICENSE,
    policy_url: CANONICAL_POLICY_URL,
    patent_warning_url: CANONICAL_PATENT_WARNING_URL,
  },
]);

/** Look up a public resource entry by kind. */
export function getPublicResourceEntry(kind: PublicResourceKind): PublicResourceEntry | undefined {
  return PUBLIC_RESOURCE_REGISTRY.find((entry) => entry.kind === kind);
}

/** Check if a string is a valid public resource kind. */
export function isPublicResourceKind(kind: string): kind is PublicResourceKind {
  return (PUBLIC_RESOURCE_KINDS as readonly string[]).includes(kind);
}

/** Check if a string is a forbidden private / workshop / moderation kind. */
export function isForbiddenPrivateResource(kind: string): boolean {
  return (
    (FORBIDDEN_PRIVATE_KINDS as readonly string[]).includes(kind) ||
    kind.startsWith("workshop") ||
    kind.startsWith("screening") ||
    kind.includes("private")
  );
}

/** List all registered public resources. */
export function listPublicResources(): readonly PublicResourceEntry[] {
  return PUBLIC_RESOURCE_REGISTRY;
}
